apiVersion: apps/v1
kind: Deployment
metadata:
  labels: &labels
    tier: $K8S_DEPLOYMENT_TIER
    framework: $K8S_DEPLOYMENT_FRAMEWORK
    app: $K8S_DEPLOYMENT_NAME
  name: $K8S_DEPLOYMENT_NAME
spec:
  replicas: $K8S_DEPLOYMENT_REPLICAS
  revisionHistoryLimit: $K8S_DEPLOYMENT_REVISION_HISTORY_LIMIT
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: $K8S_DEPLOYMENT_NAME
        image: $DOCKER_IMAGE_URI
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: $K8S_DEPLOYMENT_PORT
          initialDelaySeconds: 120
          timeoutSeconds: 40
          periodSeconds: 30
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: $K8S_DEPLOYMENT_PORT
          initialDelaySeconds: 150
          timeoutSeconds: 20
          periodSeconds: 20
          failureThreshold: 10
        ports:
        - containerPort: $K8S_DEPLOYMENT_PORT
          name: app-port
        resources:
          requests:
            memory: "$K8S_DEPLOYMENT_MEM_REQ"
            cpu: "$K8S_DEPLOYMENT_CPU_REQ"
          limits:
            memory: "$K8S_DEPLOYMENT_MEM_LIMIT"
            cpu: "$K8S_DEPLOYMENT_CPU_LIMIT"
        env:
        - name: CORS_ENABLED
          value: "$CORS_ENABLED"
        - name: CORS_ALLOWED_ADDRESSES
          value: "$CORS_ALLOWED_ADDRESSES"
        - name: JAVA_OPTS
          value: "$K8S_DEPLOYMENT_JAVA_OPTS"
        - name: MOBILE_SWITCH_SETTINGS_MS_NAME
          value: "$MOBILE_SWITCH_SETTINGS_MS_NAME"
        - name: MOBILE_SWITCH_SETTINGS_MYSQL_HOST
          value: "$MOBILE_SWITCH_SETTINGS_MYSQL_HOST"
        - name: MOBILE_SWITCH_SETTINGS_MYSQL_DB
          value: "$MOBILE_SWITCH_SETTINGS_MYSQL_DB"
        - name: MOBILE_SWITCH_SETTINGS_MYSQL_USER
          value: "$MOBILE_SWITCH_SETTINGS_MYSQL_USER"
        - name: MOBILE_SWITCH_SETTINGS_MYSQL_PASSWORD
          value: "$MOBILE_SWITCH_SETTINGS_MYSQL_PASSWORD"
        - name: KEYCLOAK_AUTH_SERVER_URL
          value : "$KEYCLOAK_AUTH_SERVER_URL"
        - name: MS_MOBILE_SWITCH_NOTIFICATION_NAME
          value: "$MS_MOBILE_SWITCH_NOTIFICATION_NAME"
        - name: MS_MOBILE_SWITCH_NOTIFICATION_API_URL
          value: "$MS_MOBILE_SWITCH_NOTIFICATION_API_URL"
        - name: MS_MOBILE_SWITCH_WALLETS_API_URL
          value: "$MS_MOBILE_SWITCH_WALLETS_API_URL"
        - name: MS_MOBILE_SWITCH_WALLETS_NAME
          value: "$MS_MOBILE_SWITCH_WALLETS_NAME"
        - name: MS_MOBILE_SWITCH_VAULT_NAME
          value: "$MS_MOBILE_SWITCH_VAULT_NAME"
        - name: MS_MOBILE_SWITCH_VAULT_API_URL
          value: "$MS_MOBILE_SWITCH_VAULT_API_URL"
        - name: NPS_LOGS_TOPIC
          value: "$NPS_LOGS_TOPIC"
        - name: KAFKA_INQUIRIES_TOPIC
          value: "$KAFKA_INQUIRIES_TOPIC"
        - name: KAFKA_CONSUMER_NOTIFICATION
          value: "$KAFKA_CONSUMER_NOTIFICATION"
        - name: AUDIT_TRAIL_TRACE_TOPIC
          value: "$AUDIT_TRAIL_TRACE_TOPIC"
        - name: AUDIT_TRAIL_SENSITIVE_DATA_TOPIC
          value: "$AUDIT_TRAIL_SENSITIVE_DATA_TOPIC"
        - name: AUDIT_TRAIL_FORBIDDEN_ACCESS_TOPIC
          value: "$AUDIT_TRAIL_FORBIDDEN_ACCESS_TOPIC"
        args: ["$K8S_DEPLOYMENT_SPRINTBOOT_PORT"]
      imagePullSecrets:
      - name: $K8S_DOCKER_IMAGE_SECRET_NAME
