apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mobile-switch-settings.fullname" . }}
  labels:
    {{- include "mobile-switch-settings.labels" . | nindent 4 }}
spec:
  {{- with .Values.strategy }}
  strategy:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mobile-switch-settings.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mobile-switch-settings.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mobile-switch-settings.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          {{- if (eq "POSTGRES" .Values.datasource.platform) }}
          - name: MOBILE_SWITCH_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "mobile-switch-settings.fullname" . }}
                key: postgresPassword
          {{- else }}
          - name: MOBILE_SWITCH_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "mobile-switch-settings.fullname" . }}
                key: mysqlPassword
          {{- end }}
          - name: TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "mobile-switch-settings.fullname" . }}
                key: trustStorePassword
          - name: KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "mobile-switch-settings.fullname" . }}
                key: keystorePassword
          envFrom:
          - configMapRef:
              name: {{ include "mobile-switch-settings.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["{{ .Values.springboot.port }}"]
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe: {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
