apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mobile-switch-settings.fullname" . }}-sql
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-7"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  mysqlPassword: "{{ .Values.datasource.db.password }}"
  postgresPassword: "{{ .Values.datasource.db.password }}"
  oraclePassword: "{{ .Values.datasource.db.password }}"
